# Generated by Django 3.2.3 on 2021-05-31 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='bookTitle',
            new_name='Book_Title',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='bookDatePublished',
            new_name='DatePublished',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='bookIsbn_Number',
            new_name='ISBN_Number',
        ),
    ]
