# Generated by Django 3.2.3 on 2021-05-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210531_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
